/* مدللني v10 — واجهة Supabase OTP والأجهزة الموثوقة */
(function () {
'use strict'
var TOKEN_KEY='mdllni_token', DEVICE_KEY='__mdllni_device__', state=null, timer=null, busy=false
function $(id){return document.getElementById(id)}
function value(id){var x=$(id);return x?String(x.value||'').trim():''}
function tell(text,kind){if(typeof window.toast==='function')return window.toast(text,kind);if(typeof window.showToast==='function')return window.showToast(text,kind);alert(text)}
function openBox(html){if(typeof window.openModal==='function')return window.openModal(html);var bg=$('modalBg'),box=$('modalBox');if(bg&&box){box.innerHTML=html;bg.classList.add('show');bg.style.display='flex'}}
function closeBox(){if(timer)clearInterval(timer);if(typeof window.closeModal==='function')return window.closeModal();var bg=$('modalBg');if(bg){bg.classList.remove('show');bg.style.display='none'}}
function setToken(token){window.TOKEN=token||null;try{token?localStorage.setItem(TOKEN_KEY,token):localStorage.removeItem(TOKEN_KEY)}catch(_){}}
window.setToken=setToken
function migrate(){try{var oldToken=['u','r','6_token'].join(''),t=localStorage.getItem(TOKEN_KEY)||localStorage.getItem(oldToken);if(t){localStorage.setItem(TOKEN_KEY,t);window.TOKEN=t}localStorage.removeItem(oldToken);var oldDevice=['__','u','r','_did__'].join(''),d=localStorage.getItem(DEVICE_KEY)||localStorage.getItem(oldDevice);if(d)localStorage.setItem(DEVICE_KEY,d);localStorage.removeItem(oldDevice)}catch(_){}}
migrate()
function deviceId(){var d='';try{d=localStorage.getItem(DEVICE_KEY)||''}catch(_){}if(!d){d=window.crypto&&crypto.randomUUID?crypto.randomUUID():'device-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,14);try{localStorage.setItem(DEVICE_KEY,d)}catch(_){}}return d}
function deviceLabel(){var u=navigator.userAgent||'',b=/Edg\//.test(u)?'Edge':/Chrome\//.test(u)?'Chrome':/Firefox\//.test(u)?'Firefox':/Safari\//.test(u)?'Safari':'متصفح',o=/Android/.test(u)?'Android':/iPhone|iPad/.test(u)?'iPhone/iPad':/Windows/.test(u)?'Windows':/Mac OS/.test(u)?'Mac':/Linux/.test(u)?'Linux':'جهاز';return b+' • '+o}
window.mdllniDeviceId=deviceId
async function auth(body){var h={'Content-Type':'application/json'};if(window.TOKEN)h.Authorization='Bearer '+window.TOKEN;var r;try{r=await fetch('/api/auth',{method:'POST',headers:h,body:JSON.stringify(body)})}catch(_){throw{error:'network_error'}}var j=await r.json().catch(function(){return{ok:false,error:'bad_response'}});if(!r.ok||!j.ok)throw j;return j}
function turnstile(kind){try{if(typeof window.getTurnstileToken==='function')return window.getTurnstileToken(kind)||'';var host=$(kind==='register'?'rgTurnstile':'lgTurnstile'),input=host&&host.querySelector('input[name="cf-turnstile-response"]');return input?input.value:''}catch(_){return''}}
function message(code,e){var m={bad_body:'راجع الحقول: رقم عراقي صحيح، بريد صحيح، كلمة مرور 8 أحرف، وجهاز مفعّل.',bad_email:'اكتب بريداً إلكترونياً صحيحاً.',weak_password:'كلمة المرور لازم تكون 8 أحرف على الأقل.',password_mismatch:'كلمتا المرور غير متطابقتين.',invalid_credentials:'رقم الهاتف أو كلمة المرور غير صحيحة.',phone_taken:'رقم الهاتف مربوط بحساب آخر.',email_taken:'البريد الإلكتروني مربوط بحساب آخر.',suspended:'الحساب موقوف. تواصل ويه الإدارة.',human_check_failed:'تعذر فحص الحماية. أعد المحاولة.',human_check_required:'أكمل فحص الحماية ثم جرّب مرة ثانية.',otp_cooldown:'انتظر دقيقة قبل طلب رمز جديد.',otp_daily_limit:'وصلت الحد اليومي للرموز. جرّب باچر أو تواصل ويه الدعم.',otp_provider_rate_limited:'Supabase أجّل إرسال البريد مؤقتاً. انتظر دقيقة.',otp_delivery_failed:'تعذر إرسال الرمز من Supabase. ما صار دخول بديل حفاظاً على حسابك.',otp_not_configured:'تحقق البريد غير مهيأ في Supabase.',otp_provider_unavailable:'تعذر الاتصال بخدمة تحقق Supabase.',otp_invalid:'الرمز غير صحيح أو منتهي.',otp_attempts_exhausted:'انتهت المحاولات الخمس. اطلب رمزاً جديداً.',otp_session_expired:'انتهت جلسة التحقق. ارجع وابدأ من جديد.',otp_identity_mismatch:'هوية البريد لا تطابق الحساب.',reset_unavailable:'هذا الحساب يحتاج ربط بريد قبل الاستعادة.',login_cooldown:'محاولات كثيرة. التبريد مؤقت وليس حظراً دائماً.',device_revoked:'هذا الجهاز ملغى. سجّل دخول وفعّله برمز البريد.',device_reauth_required:'الجلسة قديمة. سجّل دخول لتوثيق الجهاز.',email_required:'اربط بريدك أولاً حتى تكمل استخدام الحساب.',network_error:'تعذر الاتصال. تحقق من الإنترنت.',admin_not_configured:'أكمل ADMIN_EMAIL وADMIN_PASSWORD في Vercel.',cloud_not_configured:'السحابة غير مهيأة.'};var x=m[code]||('تعذر إكمال العملية: '+(code||'خطأ'));if(e&&e.retryAfter)x+=' ('+e.retryAfter+' ثانية تقريباً)';return x}
function loading(btn,on,text){if(!btn)return;if(on){btn.dataset.before=btn.innerHTML;btn.disabled=true;btn.innerHTML=text||'جارٍ التنفيذ…'}else{btn.disabled=false;if(btn.dataset.before)btn.innerHTML=btn.dataset.before}}
function ensureFields(){var p=$('rgPhone');if(p&&!$('rgEmail')){var w=p.closest('.field');if(w)w.insertAdjacentHTML('afterend','<div class="field"><label>📧 البريد الإلكتروني (رمز Supabase يوصلك عليه)</label><input id="rgEmail" type="email" dir="ltr" placeholder="name@gmail.com" autocomplete="email"></div>')}var pass=$('rgPass');if(pass)pass.placeholder='8 أحرف على الأقل';var root=$('accountRoot');if(root&&window.TOKEN&&!$('trustedDevicesBtn'))root.insertAdjacentHTML('afterbegin','<div style="display:flex;justify-content:flex-end;margin-bottom:12px"><button id="trustedDevicesBtn" class="btn btn-outline btn-sm" onclick="openTrustedDevices()">🛡️ أجهزتي الموثوقة</button></div>')}
new MutationObserver(ensureFields).observe(document.documentElement,{childList:true,subtree:true});ensureFields()
async function finish(out){if(!out||!out.token)throw{error:'bad_response'};setToken(out.token);tell(out.trustedDevice?'✅ دخول آمن من جهاز موثوق':'✅ تم تسجيل الدخول','ok');if(typeof window.refresh==='function')await window.refresh();if(typeof window.go==='function')window.go(out.role==='admin'?'#/admin':out.role==='provider'?'#/provider':'#/home')}
window.doRegister=async function(){if(busy)return;var name=value('rgName'),phone=value('rgPhone').replace(/\s/g,''),mail=value('rgEmail').toLowerCase(),pass=value('rgPass'),pass2=value('rgPass2'),area=value('rgArea'),role=window._regRole==='provider'?'provider':'customer',services=Array.prototype.map.call(document.querySelectorAll('.rgServiceCheck:checked'),function(x){return x.value}).slice(0,3),areas=Array.prototype.map.call(document.querySelectorAll('.rgArea2:checked'),function(x){return x.value}).slice(0,20);if(name.length<2)return tell('اكتب الاسم الكامل.','err');if(!/^07\d{9}$/.test(phone))return tell('اكتب رقم هاتف عراقي صحيح من 11 رقم.','err');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(mail))return tell('اكتب بريداً صحيحاً؛ رمز Supabase يوصلك عليه.','err');if(pass.length<8)return tell('كلمة المرور لازم تكون 8 أحرف على الأقل.','err');if(pass!==pass2)return tell('كلمتا المرور غير متطابقتين.','err');if(role==='provider'&&!services.length)return tell('اختر خدمة واحدة على الأقل.','err');var btn=document.querySelector('#authRoot .btn-primary.btn-block');busy=true;loading(btn,true,'جارٍ إرسال رمز Supabase…');try{var out=await auth({action:'register',name:name,phone:phone,email:mail,pass:pass,role:role,area:area,serviceIds:services,exp:value('rgExp'),areas:areas,deviceId:deviceId(),deviceLabel:deviceLabel(),turnstileToken:turnstile('register')});window._lastPhone=phone;openOtp(out)}catch(e){tell(message(e.error,e),'err')}finally{busy=false;loading(btn,false)}}
window.doLogin=async function(){if(busy)return;var phone=value('lgPhone').replace(/\s/g,''),pass=value('lgPass');if(!/^07\d{9}$/.test(phone)||!pass)return tell('اكتب رقم الهاتف وكلمة المرور.','err');var btn=document.querySelector('#authRoot .btn-primary.btn-block');busy=true;loading(btn,true,'جارٍ التحقق…');try{var out=await auth({action:'login',phone:phone,pass:pass,deviceId:deviceId(),deviceLabel:deviceLabel(),turnstileToken:turnstile('login')});window._lastPhone=phone;if(out.needsOtp)openOtp(out);else{await finish(out);if(out.needsEmail)setTimeout(window.openBindEmail,350)}}catch(e){tell(message(e.error,e),'err')}finally{busy=false;loading(btn,false)}}
function purpose(p){return p==='register'?'تفعيل الحساب':p==='device'?'توثيق الجهاز الجديد':p==='bind'?'ربط البريد':p==='reset'?'إعادة تعيين كلمة المرور':'تأكيد الدخول'}
function openOtp(out){state={pending:out.pending,purpose:out.purpose,email:out.email};renderOtp()}
function renderOtp(){openBox('<div style="text-align:center"><div style="font-size:44px">📧</div><h3>'+purpose(state.purpose)+'</h3><p style="font-size:13px;color:var(--muted)">أرسل Supabase رمزاً من 6 أرقام إلى <b dir="ltr">'+state.email+'</b></p><input id="mdOtp" inputmode="numeric" autocomplete="one-time-code" maxlength="6" dir="ltr" style="width:100%;text-align:center;font-size:30px;font-weight:900;letter-spacing:10px;padding:13px;border:2px solid var(--line);border-radius:12px" placeholder="000000"><div id="mdOtpError" style="min-height:22px;color:#b42318;font-size:13px;margin-top:8px"></div><button id="mdVerify" class="btn btn-primary btn-block" onclick="verifyMdllniOtp()">تحقق بأمان</button><button id="mdResend" class="btn btn-ghost btn-block" style="margin-top:8px" onclick="resendMdllniOtp()" disabled>إعادة الإرسال بعد 60 ثانية</button><button class="btn btn-ghost btn-sm" style="margin-top:8px" onclick="closeModal()">رجوع</button><p style="font-size:11.5px;color:var(--faint);margin-top:12px">ماكو رمز محلي ولا دخول يتجاوز Supabase.</p></div>');var i=$('mdOtp');if(i){i.focus();i.oninput=function(){this.value=this.value.replace(/\D/g,'').slice(0,6);if(this.value.length===6)window.verifyMdllniOtp()};i.onkeydown=function(e){if(e.key==='Enter')window.verifyMdllniOtp()}}countdown(60)}
function countdown(sec){if(timer)clearInterval(timer);timer=setInterval(function(){var b=$('mdResend');if(!b)return clearInterval(timer);sec--;if(sec<=0){clearInterval(timer);b.disabled=false;b.textContent='إرسال رمز جديد'}else b.textContent='إعادة الإرسال بعد '+sec+' ثانية'},1000)}
window.verifyMdllniOtp=async function(){if(busy||!state)return;var code=value('mdOtp').replace(/\D/g,'');if(code.length!==6)return $('mdOtpError').textContent='اكتب الأرقام الستة.';var btn=$('mdVerify');busy=true;loading(btn,true,'جارٍ التحقق من Supabase…');try{if(state.purpose==='reset')return await completeReset(code);var wasBind=state.purpose==='bind',out=await auth({action:'verifyOtp',pending:state.pending,code:code});closeBox();state=null;await finish(out);if(wasBind)tell('✅ تم ربط البريد وتوثيق الحساب.','ok')}catch(e){if($('mdOtpError'))$('mdOtpError').textContent=message(e.error,e)}finally{busy=false;loading(btn,false)}}
window.resendMdllniOtp=async function(){if(busy||!state)return;var btn=$('mdResend');busy=true;loading(btn,true,'جارٍ الإرسال…');try{var out=await auth({action:'resendOtp',pending:state.pending});state.pending=out.pending;state.email=out.email;tell('✅ أرسل Supabase رمزاً جديداً.','ok');countdown(60)}catch(e){if($('mdOtpError'))$('mdOtpError').textContent=message(e.error,e)}finally{busy=false;loading(btn,false)}}
window.openForgotPasswordModal=function(){openBox('<h3>🔑 استعادة كلمة المرور</h3><p style="font-size:13px;color:var(--muted)">يرسل Supabase رمزاً إلى البريد الموثق.</p><div class="field"><label>رقم الهاتف</label><input id="mdResetPhone" value="'+(window._lastPhone||'')+'" inputmode="tel" placeholder="07XXXXXXXXX"></div><button id="mdResetSend" class="btn btn-primary btn-block" onclick="sendMdllniReset()">إرسال رمز الاستعادة</button>')}
window.sendMdllniReset=async function(){if(busy)return;var btn=$('mdResetSend');busy=true;loading(btn,true,'جارٍ الإرسال…');try{var out=await auth({action:'forgotPassword',phone:value('mdResetPhone'),deviceId:deviceId(),deviceLabel:deviceLabel()});state={pending:out.pending,purpose:'reset',email:out.email};openBox('<h3>🔐 كلمة مرور جديدة</h3><p style="font-size:13px;color:var(--muted)">اكتب رمز Supabase وكلمة مرور من 8 أحرف.</p><div class="field"><label>رمز التحقق</label><input id="mdOtp" maxlength="6" inputmode="numeric" autocomplete="one-time-code" dir="ltr"></div><div class="field"><label>كلمة المرور الجديدة</label><input id="mdNewPass" type="password" autocomplete="new-password"></div><div class="field"><label>تأكيدها</label><input id="mdNewPass2" type="password" autocomplete="new-password"></div><div id="mdOtpError" style="min-height:22px;color:#b42318"></div><button id="mdVerify" class="btn btn-primary btn-block" onclick="verifyMdllniOtp()">تغييرها بأمان</button>')}catch(e){tell(message(e.error,e),'err')}finally{busy=false;loading(btn,false)}}
async function completeReset(code){var p1=value('mdNewPass'),p2=value('mdNewPass2');if(p1.length<8)throw{error:'weak_password'};if(p1!==p2)throw{error:'password_mismatch'};var out=await auth({action:'resetPassword',pending:state.pending,code:code,newPass:p1});closeBox();state=null;await finish(out);tell('✅ تغيرت كلمة المرور وأُلغيت الجلسات القديمة.','ok')}
window.openBindEmail=function(){openBox('<h3>📧 ربط بريد الحساب</h3><p style="font-size:13px;color:var(--muted)">خطوة إلزامية للحسابات القديمة، والرمز من Supabase فقط.</p><div class="field"><label>البريد الإلكتروني</label><input id="mdBindEmail" type="email" dir="ltr" placeholder="name@gmail.com"></div><button id="mdBindSend" class="btn btn-primary btn-block" onclick="sendMdllniBind()">إرسال رمز التحقق</button>')}
window.sendMdllniBind=async function(){if(busy)return;var btn=$('mdBindSend');busy=true;loading(btn,true,'جارٍ الإرسال…');try{openOtp(await auth({action:'bindEmail',email:value('mdBindEmail'),deviceId:deviceId(),deviceLabel:deviceLabel()}))}catch(e){tell(message(e.error,e),'err')}finally{busy=false;loading(btn,false)}}
window.openTrustedDevices=async function(){try{var out=await auth({action:'me'}),rows=(out.devices||[]).map(function(d){var exp=d.trusted_until?new Date(d.trusted_until).toLocaleDateString('ar-IQ'):'يحتاج تحقق';return'<div style="padding:12px;border:1px solid var(--line);border-radius:12px;margin:8px 0;display:flex;gap:10px;align-items:center"><div style="font-size:26px">'+(d.current?'📱':'💻')+'</div><div style="flex:1"><b>'+(d.label||'جهاز')+(d.current?' — هذا الجهاز':'')+'</b><div style="font-size:12px;color:var(--muted)">'+d.status+' · الثقة لغاية '+exp+'</div></div>'+(d.status==='active'?'<button class="btn btn-ghost btn-sm" onclick="revokeTrustedDevice(\''+d.id+'\','+(d.current?'true':'false')+')">إلغاء</button>':'')+'</div>'}).join('');openBox('<h3>🛡️ أجهزتي الموثوقة</h3><p style="font-size:13px;color:var(--muted)">حد أقصى 3 أجهزة؛ الرابع يستبدل الأقدم تلقائياً.</p>'+(rows||'<p>لا توجد أجهزة.</p>'))}catch(e){tell(message(e.error,e),'err')}}
window.revokeTrustedDevice=async function(id,current){if(!confirm(current?'إلغاء هذا الجهاز راح يطلعك من الحساب. متأكد؟':'إلغاء هذا الجهاز؟'))return;try{var out=await auth({action:'revokeMyDevice',deviceId:id});if(out.logout||current){setToken(null);closeBox();location.hash='#/auth/login';return location.reload()}await window.openTrustedDevices();tell('تم إلغاء الجهاز وجلساته.','ok')}catch(e){tell(message(e.error,e),'err')}}
window.exportData=function(){try{var blob=new Blob([JSON.stringify(window.DB||{},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mdllni-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)}catch(_){tell('تعذر إنشاء النسخة الاحتياطية.','err')}}
if(window.TOKEN&&typeof window.refresh==='function')setTimeout(function(){window.refresh().catch(function(){})},0)
})()
