'use strict'
const fs=require('fs'),path=require('path'),assert=require('assert')
const root=path.join(__dirname,'..');let n=0
function test(name,fn){try{fn();n++;console.log('✓',name)}catch(e){console.error('✗',name,'\n ',e.message);process.exitCode=1}}
function read(p){return fs.readFileSync(path.join(root,p),'utf8')}
const auth=read('api/auth.js'),data=read('api/data.js'),ui=read('js/cloud-patch.js'),health=read('api/health.js'),index=read('index.html'),env=read('.env.example'),migration=read('supabase/migrations/20260918143000_v13_mdllni_identity_rebrand.sql')
process.env.JWT_SECRET='x'.repeat(64)
const lib=require('../api/_lib')
test('password hash is salted scrypt',()=>{const a=lib.hashPassword('Password123!'),b=lib.hashPassword('Password123!');assert.notStrictEqual(a,b);assert(lib.verifyPassword('Password123!',a));assert(!lib.verifyPassword('wrong',a))})
test('JWT round trip and tamper rejection',()=>{const t=lib.signToken({sub:'u1',dv:'d1'},1);assert.strictEqual(lib.verifyToken(t).sub,'u1');assert.strictEqual(lib.verifyToken(t.slice(0,-1)+'x'),null)})
test('no external mail module',()=>{assert(!auth.includes("require('./_mail')"));assert(!auth.includes('sendOtpEmail'))})
test('no direct reset endpoint',()=>{assert(!auth.includes('directResetPassword'));assert(!auth.includes('confirmEmailToken'))})
test('OTP is issued only by Supabase endpoint',()=>{assert(auth.includes("supa('otp'"));assert(!auth.includes('Math.random() * 1000000'))})
test('OTP is verified by Supabase as email type',()=>{assert(auth.includes("supa('verify', { type: 'email'"))})
test('no direct-login fallback after email failure',()=>{const block=auth.slice(auth.indexOf('async function sendOtp'),auth.indexOf('function makePending'));assert(block.includes("fail(503, 'otp_delivery_failed')"));assert(!/session\s*\(/.test(block))})
test('reset verifies OTP before password update',()=>{const block=auth.slice(auth.indexOf('async function reset('),auth.indexOf('async function me('));assert(block.indexOf('await verifyOtp')>=0);assert(block.indexOf('await verifyOtp')<block.indexOf('pass_hash'))})
test('registration creates profile only after OTP',()=>{assert(auth.indexOf('const user = await verifyOtp')<auth.indexOf('await createRegistration'))})
test('OTP pending token is purpose and jti bound',()=>{assert(auth.includes("scope: 'otp', jti: rid()"));assert(auth.includes('OTP_DAYS = 10 / 1440'))})
test('five OTP attempts maximum',()=>{assert(auth.includes('attempts >= 5'));assert(auth.includes('otp_attempts_exhausted'))})
test('adaptive trust is 30 days and admin 7',()=>{assert(auth.includes('TRUST_DAYS = 30'));assert(auth.includes('ADMIN_TRUST_DAYS = 7'))})
test('maximum three trusted devices',()=>{assert(auth.includes('MAX_DEVICES = 3'));assert(auth.includes('device_rotated'))})
test('shared device is a signal, not a hard ban',()=>{assert(auth.includes('shared_device_verified'));assert(!auth.includes('device_in_use'))})
test('login cooldown is account plus hashed network',()=>{assert(auth.includes("'login:' + profileId + ':' + sha256"));assert(auth.includes('60000'));assert(auth.includes('900000'));assert(auth.includes('3600000'))})
test('admin has no device exemption in data gateway',()=>{assert(!data.includes("viewer.role === 'admin'"));assert(data.includes("status: 'active'"));assert(data.includes('device_revoked'))})
test('limited legacy session cannot mutate data',()=>{assert(data.includes('payload.limited'));assert(data.includes('email_required'))})
test('UI always carries device id and email',()=>{assert(ui.includes('__mdllni_device__'));assert(ui.includes("action:'register'"));assert(ui.includes("value('rgEmail')"));assert(ui.includes('MutationObserver'))})
test('UI supports recovery only with OTP',()=>{assert(ui.includes("action:'forgotPassword'"));assert(ui.includes("action:'resetPassword'"));assert(ui.includes('verifyMdllniOtp'))})
test('UI has self-service revoke',()=>{assert(ui.includes("action:'revokeMyDevice'"));assert(ui.includes('openTrustedDevices'))})
test('health declares Supabase provider',()=>{assert(health.includes("authProvider: 'supabase-email-otp'"));assert(health.includes("version: 'v10'"))})
test('all four assets are cache-busted to v10',()=>{assert.strictEqual((index.match(/v=10\.0\.0/g)||[]).length,4)})
test('environment contains no external mail settings',()=>{assert(!/^MAIL_/m.test(env));assert(env.includes('SUPABASE_PUBLISHABLE_KEY'))})
test('migration removes local OTP table',()=>{assert(migration.includes('drop table if exists public.ur_email_otps cascade'))})
test('migration renames tables without copying financial rows',()=>{assert(migration.includes('alter table public.%I rename to %I'));assert(!/delete from public\.ur_(orders|ledger|payouts)/.test(migration))})
test('migration preserves atomic debt function',()=>{assert(migration.includes('create or replace function public.mdllni_apply_debt'));assert(migration.includes('on conflict do nothing'))})
test('migration links confirmed admin auth identity',()=>{assert(migration.includes('auth_user_id'));assert(migration.includes('email_confirmed_at'))})
test('migration removes global device uniqueness',()=>{assert(migration.includes('drop index if exists public.mdllni_devices_active_fp'));assert(migration.includes('mdllni_devices_profile_fp_active'))})
test('migration rejects leftover runtime names',()=>{assert(migration.includes('Legacy runtime objects remain'))})
if(process.exitCode)process.exit(1);console.log('\n'+n+'/'+n+' security checks passed')
