// مدللني v11 — طبقة أمان فوق محرك الأعمال القديم.
'use strict'
const legacy = require('./_engine')
const { dal } = require('./_lib')
function fail(status,code){const e=new Error(code);e.status=status;e.code=code;throw e}
async function securityEvent(profileId,kind,meta){try{await dal.insert('mdllni_security_events',{profile_id:profileId||null,kind,meta:meta||{},ip:'',created_at:new Date().toISOString()})}catch(_){}}
async function notify(userId,icon,body,orderId){try{await dal.insert('mdllni_notifications',{user_id:userId,icon,body,order_id:orderId||null,read:false,created_at:new Date().toISOString()})}catch(_){}}
async function callRpc(name,args){try{return await dal.rpc(name,args)}catch(error){const tail=String(error&&error.message||'').split(':').pop().trim();if(/^[a-z][a-z0-9_]{2,80}$/.test(tail))error.code=tail;throw error}}
function timelineAt(order,status){const rows=Array.isArray(order.timeline)?order.timeline:[];for(let i=rows.length-1;i>=0;i--){if(rows[i]&&rows[i].s===status){const value=Number(rows[i].at)||Date.parse(String(rows[i].at||''));if(Number.isFinite(value))return value}}return 0}
async function runAction(actor,action,payload){payload=payload||{};if(['changePassword','adjustDebt','adminAdjustDebt','debtAdjustment'].includes(action))fail(400,action==='changePassword'?'password_change_requires_otp':'financial_adjustment_requires_review');if(action==='providerDrop'){const order=await dal.find('mdllni_orders',{id:payload.orderId});if(order&&order.provider_id===actor.id){if(['enroute','started'].includes(order.status)){await securityEvent(actor.id,'active_order_drop_blocked',{order_id:order.id,status:order.status});fail(409,'active_drop_requires_dispute')}if(order.status==='accepted'){const acceptedAt=timelineAt(order,'accepted'),messages=await dal.all('mdllni_order_messages',{order_id:order.id}),extras=Array.isArray(order.extras)?order.extras:[];if(!acceptedAt||Date.now()-acceptedAt>15*60*1000||messages.length||extras.length||order.disputed){await securityEvent(actor.id,'accepted_order_drop_blocked',{order_id:order.id,accepted_at:acceptedAt,messages:messages.length,extras:extras.length});fail(409,'accepted_drop_requires_review')}const result=await legacy.runAction(actor,action,payload);await securityEvent(actor.id,'accepted_order_drop_allowed',{order_id:order.id,within_minutes:15,reason:String(payload.reason||'').slice(0,160)});return result}}}if(action==='advanceOrder'){const order=await dal.find('mdllni_orders',{id:payload.orderId});if(order&&order.status==='started'){const result=await callRpc('mdllni_complete_order',{p_order:order.id,p_actor:actor.id});await notify(order.customer_id,'✅','اكتملت الخدمة للطلب '+order.id+'. إذا عندك اعتراض افتح نزاع فوراً.',order.id);await notify(order.provider_id,'🧾','تم توثيق إكمال الطلب '+order.id+' والعمولة والذمة ذرياً.',order.id);return result||{}}}if(action==='confirmSettlement'){const payoutId=String(payload.payoutId||'');if(!payoutId)fail(400,'payout_unavailable');const result=await callRpc('mdllni_confirm_settlement',{p_payout:payoutId,p_actor:actor.id});if(result&&result.providerId)await notify(result.providerId,'✅','تم تأكيد السداد '+payoutId+' وتحديث الذمة ذرياً.',null);return result||{}}return await legacy.runAction(actor,action,payload)}
module.exports={snapshot:legacy.snapshot,runAction,provisionAdmin:legacy.provisionAdmin}
