// مدللني v11 — Supabase OTP فقط، حدود ذرية، وإصدارات جلسة لكل جهاز.
'use strict'
const core = require('./auth')
const { dal, signToken, verifyToken, sha256 } = require('./_lib')
const { requireActiveSession, failure } = require('./_session-v11')
const OTP_ACTIONS = new Set(['register','login','verifyOtp','resendOtp','bindEmail','forgotPassword','resetPassword'])
const MAX_BODY = 262144
function headersFor(req){const h={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization',Vary:'Origin'};const origin=String(req.headers.origin||''),allowed=String(process.env.APP_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);if(origin&&allowed.includes(origin))h['Access-Control-Allow-Origin']=origin;return h}
function send(req,res,status,body,inherited){const h=Object.assign({},inherited||{},headersFor(req));delete h['Access-Control-Allow-Origin'];delete h['access-control-allow-origin'];const secure=headersFor(req);if(secure['Access-Control-Allow-Origin'])h['Access-Control-Allow-Origin']=secure['Access-Control-Allow-Origin'];for(const[k,v]of Object.entries(h))res.setHeader(k,v);res.statusCode=status;res.end(status===204?undefined:JSON.stringify(body||{}))}
function captureResponse(){return{statusCode:200,headers:{},body:'',setHeader(k,v){this.headers[k]=v},getHeader(k){return this.headers[k]},end(v){this.body=v==null?'':String(v);this.ended=true}}}
function parseCaptured(r){try{return r.body?JSON.parse(r.body):{}}catch(_){return{ok:false,error:'invalid_server_response'}}}
function phone(v){let s=String(v||'').replace(/[^0-9+]/g,'');if(s.startsWith('+964'))s='0'+s.slice(4);else if(s.startsWith('964'))s='0'+s.slice(3);return s}
function network(req){return String(req.headers['x-forwarded-for']||req.headers['x-real-ip']||'unknown').split(',')[0].trim().slice(0,80)}
async function readLimitedBody(req){if(req.body!=null){const raw=typeof req.body==='string'?req.body:JSON.stringify(req.body);if(Buffer.byteLength(raw)>MAX_BODY)throw failure(413,'body_too_large');if(typeof req.body==='string'){try{return JSON.parse(req.body)}catch(_){throw failure(400,'bad_json')}}return req.body}return await new Promise((resolve,reject)=>{let text='',size=0,large=false;req.on('data',chunk=>{size+=chunk.length;if(size>MAX_BODY){large=true;return}text+=chunk});req.on('end',()=>{if(large)return reject(failure(413,'body_too_large'));try{resolve(text?JSON.parse(text):{})}catch(_){reject(failure(400,'bad_json'))}});req.on('error',()=>reject(failure(400,'bad_body')))})}
async function limitRow(key){return await dal.find('mdllni_rate_limits',{key})}
function blockedUntil(row){if(!row||Date.now()-Number(row.first||0)>3600000)return 0;return Number(Array.isArray(row.items)&&row.items[0]||0)}
async function bumpFailure(key,scope){const row=await dal.rpc('mdllni_login_failure',{p_key:key,p_now_ms:Date.now(),p_scope:scope});return{count:Number(row&&row.count||0),until:Number(row&&row.until||0)}}
async function bumpWindow(key,windowMs){return await dal.rpc('mdllni_rate_bump',{p_key:key,p_now_ms:Date.now(),p_window_ms:windowMs})}
async function reserveOtpSend(req,action,body,pending,profile){let target='';if(action==='register'||action==='bindEmail')target=String(body.email||'').trim().toLowerCase();else if(action==='forgotPassword')target=String(profile&&profile.email||'').trim().toLowerCase();else if(action==='resendOtp')target=String(pending&&pending.e||'').trim().toLowerCase();if(!target)return;const targetRow=await bumpWindow('otp-send:v11:target:'+sha256(target).slice(0,32),3600000);if(Number(targetRow&&targetRow.count||0)>5)throw failure(429,'otp_send_cooldown');const networkRow=await bumpWindow('otp-send:v11:network:'+sha256(network(req)).slice(0,24),3600000);if(Number(networkRow&&networkRow.count||0)>30)throw failure(429,'otp_network_cooldown');if(action==='resendOtp'&&pending&&pending.jti){const pendingRow=await bumpWindow('otp-resend:v11:'+pending.jti,600000);if(Number(pendingRow&&pendingRow.count||0)>3)throw failure(429,'otp_resend_cooldown')}}
async function requireBoundSession(req,pending){const session=await requireActiveSession(req,{allowLimited:true});if(pending&&(pending.sub!==session.profile.id||pending.fp!==session.payload.dv))throw failure(401,'unauthorized');return session}
async function signCurrentSession(output,action){const tokenPayload=verifyToken(output.token);if(!tokenPayload||!tokenPayload.sub||!tokenPayload.dv)throw failure(500,'invalid_server_token');const profile=await dal.find('mdllni_profiles',{id:tokenPayload.sub});if(!profile||profile.status!=='active')throw failure(401,'unauthorized');if(!tokenPayload.limited&&(!profile.email_verified||!profile.auth_user_id))throw failure(409,'auth_identity_unlinked');const device=await dal.find('mdllni_devices',{profile_id:profile.id,fingerprint:tokenPayload.dv,status:'active'});if(!device)throw failure(401,'device_revoked');const trust=Date.parse(String(device.trusted_until||''));if(!Number.isFinite(trust)||trust<=Date.now())throw failure(401,'device_trust_expired');let version=Number(device.session_version);if(!Number.isSafeInteger(version)||version<1)throw failure(401,'device_reauth_required');if(action==='verifyOtp'||action==='resetPassword'){const next=version+1,updated=await dal.update('mdllni_devices',{id:device.id,session_version:version},{session_version:next,last_seen:new Date().toISOString()});if(!updated||updated.length!==1)throw failure(409,'session_rotation_race');version=next}delete tokenPayload.iat;delete tokenPayload.exp;tokenPayload.sub=profile.id;tokenPayload.role=profile.role;tokenPayload.phone=profile.phone;tokenPayload.sv=version;output.userId=profile.id;output.role=profile.role;output.token=signToken(tokenPayload,profile.role==='admin'?7:30)}
module.exports=async function authV11(req,res){const base=headersFor(req);try{if(req.method==='OPTIONS'){if(req.headers.origin&&!base['Access-Control-Allow-Origin'])return send(req,res,403,{ok:false,error:'origin_not_allowed'});return send(req,res,204)}if(req.method!=='POST')return send(req,res,405,{ok:false,error:'method_not_allowed'});if(Number(req.headers['content-length']||0)>MAX_BODY)return send(req,res,413,{ok:false,error:'body_too_large'});const body=await readLimitedBody(req);req.body=body;const action=String(body.action||'');if(OTP_ACTIONS.has(action)&&!String(process.env.SUPABASE_PUBLISHABLE_KEY||'').trim())return send(req,res,503,{ok:false,error:'otp_not_configured'});const pending=body.pending?verifyToken(String(body.pending)):null;if(['bindEmail','me','revokeMyDevice'].includes(action))await requireBoundSession(req);if(pending&&pending.scope==='otp'&&pending.p==='bind'&&['verifyOtp','resendOtp'].includes(action))await requireBoundSession(req,pending);let attemptKey='';if(pending&&pending.scope==='otp'&&pending.jti&&['verifyOtp','resetPassword'].includes(action)){attemptKey='otp:v11:'+pending.jti;const attempt=await bumpWindow(attemptKey,600000);if(Number(attempt&&attempt.count||0)>5)return send(req,res,429,{ok:false,error:'otp_attempts_exhausted'})}let profile=null;if(['login','forgotPassword'].includes(action))profile=await dal.find('mdllni_profiles',{phone:phone(body.phone)});let accountKey='';const netKey='login:v11:network:'+sha256(network(req)).slice(0,24);if(action==='login'){if(profile)accountKey='login:v11:account:'+profile.id;for(const key of[accountKey,netKey].filter(Boolean)){const until=blockedUntil(await limitRow(key));if(until>Date.now())return send(req,res,429,{ok:false,error:'login_cooldown',retryAfter:Math.ceil((until-Date.now())/1000)})}}if(['register','resendOtp','bindEmail','forgotPassword'].includes(action))await reserveOtpSend(req,action,body,pending,profile);const captured=captureResponse();await core(req,captured);const output=parseCaptured(captured);if(action==='login'&&captured.statusCode===401&&output.error==='invalid_credentials'){const failures=[];if(accountKey)failures.push(await bumpFailure(accountKey,'account'));failures.push(await bumpFailure(netKey,'network'));const until=failures.reduce((m,x)=>Math.max(m,x.until||0),0);if(until>Date.now()){captured.statusCode=429;output.error='login_cooldown';output.retryAfter=Math.ceil((until-Date.now())/1000)}}else if(action==='login'&&captured.statusCode<300&&accountKey){try{await dal.del('mdllni_rate_limits',{key:accountKey})}catch(_){}}if(captured.statusCode<300&&attemptKey){try{await dal.del('mdllni_rate_limits',{key:attemptKey})}catch(_){}}if(captured.statusCode<300&&output.token)await signCurrentSession(output,action);return send(req,res,captured.statusCode||200,output,captured.headers)}catch(error){return send(req,res,error.status||500,{ok:false,error:error.code||error.message||'server_error'})}}
