// مدللني v11 — بوابة بيانات سحابية بحد جسم صارم وSnapshot عام معزول.
'use strict'
const { getToken } = require('./_lib')
const { requireActiveSession, failure } = require('./_session-v11')
const { sanitizeSnapshot } = require('./_snapshot-v11')
const { snapshot, publicSnapshot, runAction } = require('./_engine-v11')
const MAX_BODY = 262144
function responseHeaders(req){const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Cache-Control':'no-store',Vary:'Origin'};const origin=String(req.headers.origin||''),allowed=String(process.env.APP_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);if(origin&&allowed.includes(origin))headers['Access-Control-Allow-Origin']=origin;return headers}
function send(req,res,status,body){for(const[k,v]of Object.entries(responseHeaders(req)))res.setHeader(k,v);res.statusCode=status;res.end(status===204?undefined:JSON.stringify(body||{}))}
async function readLimitedBody(req){if(req.body!=null){const raw=typeof req.body==='string'?req.body:JSON.stringify(req.body);if(Buffer.byteLength(raw)>MAX_BODY)throw failure(413,'body_too_large');if(typeof req.body==='string'){try{return JSON.parse(req.body)}catch(_){throw failure(400,'bad_json')}}return req.body}return await new Promise((resolve,reject)=>{let text='',size=0,large=false;req.on('data',chunk=>{size+=chunk.length;if(size>MAX_BODY){large=true;return}text+=chunk});req.on('end',()=>{if(large)return reject(failure(413,'body_too_large'));try{resolve(text?JSON.parse(text):{})}catch(_){reject(failure(400,'bad_json'))}});req.on('error',()=>reject(failure(400,'bad_body')))})}
module.exports=async function(req,res){try{if(req.method==='OPTIONS'){const h=responseHeaders(req);if(req.headers.origin&&!h['Access-Control-Allow-Origin'])return send(req,res,403,{ok:false,error:'origin_not_allowed'});return send(req,res,204)}if(req.method!=='POST')return send(req,res,405,{ok:false,error:'method_not_allowed'});if(Number(req.headers['content-length']||0)>MAX_BODY)return send(req,res,413,{ok:false,error:'body_too_large'});const body=await readLimitedBody(req),action=String(body.action||req.query&&req.query.action||'snapshot');let session=null;if(getToken(req))session=await requireActiveSession(req,{allowLimited:action==='snapshot'});const viewer=session&&session.profile;if(action==='snapshot'){const db=viewer?await snapshot(viewer):await publicSnapshot();return send(req,res,200,{ok:true,db:sanitizeSnapshot(db,viewer)})}if(!session)return send(req,res,401,{ok:false,error:'unauthorized'});if(session.payload.limited)return send(req,res,403,{ok:false,error:'email_required'});const result=await runAction(viewer,action,body.payload||{}),db=sanitizeSnapshot(await snapshot(viewer),viewer);return send(req,res,200,{ok:true,result,db})}catch(error){return send(req,res,error.status||500,{ok:false,error:error.code||error.message||'server_error'})}}
