// مدللني v11 — بوابة البيانات المحمية بجلسة وجهاز وثقة زمنية.
'use strict'
const { readBody, getToken } = require('./_lib')
const { requireActiveSession } = require('./_session-v11')
const { sanitizeSnapshot } = require('./_snapshot-v11')
const { snapshot, runAction } = require('./_engine-v11')
function responseHeaders(req){const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization',Vary:'Origin'};const origin=String(req.headers.origin||'');const allowed=String(process.env.APP_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);if(origin&&allowed.includes(origin))headers['Access-Control-Allow-Origin']=origin;return headers}
function send(req,res,status,body){for(const[key,value]of Object.entries(responseHeaders(req)))res.setHeader(key,value);res.statusCode=status;res.end(status===204?undefined:JSON.stringify(body||{}))}
module.exports=async function dataV11(req,res){try{if(req.method==='OPTIONS'){const headers=responseHeaders(req);if(req.headers.origin&&!headers['Access-Control-Allow-Origin'])return send(req,res,403,{ok:false,error:'origin_not_allowed'});return send(req,res,204)}if(req.method!=='POST')return send(req,res,405,{ok:false,error:'method_not_allowed'});if(Number(req.headers['content-length']||0)>262144)return send(req,res,413,{ok:false,error:'body_too_large'});const body=await readBody(req);const action=String(body.action||req.query&&req.query.action||'snapshot');let session=null;if(getToken(req))session=await requireActiveSession(req,{allowLimited:action==='snapshot'});const viewer=session&&session.profile;if(action==='snapshot'){const db=await snapshot(viewer);return send(req,res,200,{ok:true,db:sanitizeSnapshot(db,viewer)})}if(!session)return send(req,res,401,{ok:false,error:'unauthorized'});if(session.payload.limited)return send(req,res,403,{ok:false,error:'email_required'});const result=await runAction(viewer,action,body.payload||{});const db=sanitizeSnapshot(await snapshot(viewer),viewer);return send(req,res,200,{ok:true,result,db})}catch(error){return send(req,res,error.status||500,{ok:false,error:error.code||error.message||'server_error'})}}
